name: alarm_calendar
description: "Alarm calendar app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  just_audio: ^0.10.4
  # Используем версию file_picker без проблем с совместимостью
  file_picker: ^10.3.1
  path_provider: ^2.1.2
  equatable: ^2.0.5
  # Используем более старую версию flutter_local_notifications
  flutter_local_notifications: ^19.4.0
  # Используем версию timezone, совместимую с flutter_local_notifications 9.9.1
  timezone: ^0.10.1
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/sounds/
    - assets/images/