name: alarm_calendar
description: "Alarm calendar app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  just_audio: ^0.9.37
  file_picker: ^10.3.2
  path_provider: ^2.1.3
  equatable: ^2.0.5
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/sounds/
    - assets/images/